name: Telegram Release Notification

on:
  release:
    types: [published]

jobs:
  telegram-release-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Release Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ğŸ‰ *Novo Release Publicado!*
            
            ğŸ“¦ *RepositÃ³rio:* `${{ github.repository }}`
            ğŸ·ï¸ *VersÃ£o:* `${{ github.event.release.tag_name }}`
            ğŸ§¾ *Nome:* `${{ github.event.release.name }}`
            ğŸ—’ï¸ *DescriÃ§Ã£o:*
            ${{ github.event.release.body }}
            
            ğŸ”— [Ver Release](${{ github.event.release.html_url }})
          format: markdown
