name: Telegram Commit Notification

on:
  push:
    branches:
      - main

jobs:
  telegram-commit-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Commit Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ğŸ“¢ *Novo commit no repositÃ³rio:* `${{ github.repository }}`
            
            ğŸ§‘ *Autor:* ${{ github.actor }}
            
            ğŸ“ *Mensagem:* ${{ github.event.head_commit.message }}
            
            ğŸ”— [Ver commit](${{ github.event.head_commit.url }})
          format: markdown